# Generated by Django 5.2.1 on 2025-05-30 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_notes',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='bottle_size',
            field=models.IntegerField(db_default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='concertration',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='fragrance_family',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='heart_notes',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='longevity',
            field=models.CharField(choices=[('weak', 'Weak'), ('medium', 'Medium'), ('strong', 'Strong')], default='Moderate', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='perfumer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='release_year',
            field=models.IntegerField(db_default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sillage',
            field=models.CharField(choices=[('close', 'Close'), ('medium', 'Medium'), ('strong', 'Strong')], default='Moderate', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='top_notes',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('kids', 'Kids'), ('unisex', 'Unisex')], max_length=40),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product'),
        ),
    ]
