# Generated by Django 5.2.1 on 2025-06-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_notes_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_notes',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='heart_notes',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_notes',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
