# Generated by Django 5.2.1 on 2025-06-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_base_notes_alter_product_heart_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='notes',
        ),
        migrations.AlterField(
            model_name='product',
            name='base_notes',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='heart_notes',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_notes',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
